name = "fortplot"
version = "2025.06.25"
license = "license"
author = "Christopher Albert"
maintainer = "albert@alumni.tugraz.at"
copyright = "Copyright 2025, Christopher Albert"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[extra.ford]
project = "fortplotlib"
src_dir = "src"
output_dir = "build/doc"
page_dir = "doc"
