name = "fortplotlib_example"
version = "1.0.0"
license = "MIT"
author = "Fortplotlib Example"

[build]
auto-executables = true

[dependencies]
# Use fortplotlib as a git dependency
fortplotlib = { git = "https://github.com/krystophny/fortplotlib.git" }

# Alternative: use local path during development
# fortplotlib = { path = "../.." }