name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gfortran-11, gfortran-12, gfortran-13, gfortran-14]
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Fortran Package Manager
      run: |
        wget https://github.com/fortran-lang/fpm/releases/download/v0.12.0/fpm-0.12.0-linux-x86_64-gcc-12
        chmod +x fpm-0.12.0-linux-x86_64-gcc-12
        sudo mv fpm-0.12.0-linux-x86_64-gcc-12 /usr/local/bin/fpm

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.compiler }} cmake make ffmpeg pngcheck python3-pil

    - name: Set compiler
      run: |
        if [ "${{ matrix.compiler }}" = "gfortran-11" ]; then
          echo "FC=gfortran-11" >> $GITHUB_ENV
          echo "FPM_FC=gfortran-11" >> $GITHUB_ENV
        elif [ "${{ matrix.compiler }}" = "gfortran-12" ]; then
          echo "FC=gfortran-12" >> $GITHUB_ENV
          echo "FPM_FC=gfortran-12" >> $GITHUB_ENV
        elif [ "${{ matrix.compiler }}" = "gfortran-13" ]; then
          echo "FC=gfortran-13" >> $GITHUB_ENV
          echo "FPM_FC=gfortran-13" >> $GITHUB_ENV
        elif [ "${{ matrix.compiler }}" = "gfortran-14" ]; then
          echo "FC=gfortran-14" >> $GITHUB_ENV
          echo "FPM_FC=gfortran-14" >> $GITHUB_ENV
        fi

    - name: Build project
      run: |
        make build

    - name: Build required examples for tests
      run: |
        make example ARGS="basic_plots"
        make example ARGS="legend_demo"
        make example ARGS="contour_demo"
        make example ARGS="marker_demo"
        make example ARGS="format_string_demo"

    - name: Run all tests
      run: |
        export FORTPLOT_ENABLE_FFMPEG=0
        export OMP_NUM_THREADS=2
        mkdir -p /tmp/test
        timeout 30m make test

    - name: Test FPM example
      run: |
        make test ARGS="--target test_system_fpm_example"

    - name: Test CMake example  
      run: |
        make test ARGS="--target test_system_cmake_example"

    # TODO: Enable after PNG encoder fix (Issue #96)
    # - name: PNG Validation Tests
    #   run: |
    #     make test ARGS="test_png_validation"

  build-cmake:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran cmake ffmpeg

    - name: Test CMake build
      run: |
        cd doc/cmake_example
        mkdir -p build
        cd build
        cmake ..
        make
        ./fortplot_test