name: Deploy Documentation

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Fortran Package Manager
      run: |
        wget https://github.com/fortran-lang/fpm/releases/download/v0.12.0/fpm-0.12.0-linux-x86_64-gcc-12
        chmod +x fpm-0.12.0-linux-x86_64-gcc-12
        sudo mv fpm-0.12.0-linux-x86_64-gcc-12 /usr/local/bin/fpm

    - name: Install GFortran and FORD
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran
        pip install ford

    - name: Build project
      run: make build

    - name: Build documentation
      run: make doc

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        deploy_key: ${{ secrets.DOCS_DEPLOY_KEY }}
        external_repository: krystophny/fortplotlib.github.io
        publish_branch: main
        publish_dir: ./build/doc
        destination_dir: .
        cname: fortplotlib.github.io