name: Deploy Documentation

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install FORD
      run: pip install ford

    - name: Build documentation
      run: make doc

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.DOCS_PAT }}
        external_repository: krystophny/fortplotlib.github.io
        publish_branch: main
        publish_dir: ./build/doc
        destination_dir: .
        cname: fortplotlib.github.io