name: Test Coverage

on: [push, pull_request]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Fortran Package Manager
      run: |
        wget https://github.com/fortran-lang/fpm/releases/download/v0.12.0/fpm-0.12.0-linux-x86_64-gcc-12
        chmod +x fpm-0.12.0-linux-x86_64-gcc-12
        sudo mv fpm-0.12.0-linux-x86_64-gcc-12 /usr/local/bin/fpm

    - name: Install GFortran, CMake and gcov
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran gcovr cmake ffmpeg

    - name: Build with coverage flags
      run: |
        make build ARGS="--flag '-fprofile-arcs -ftest-coverage'"

    - name: Run FPM tests with coverage
      run: |
        make test ARGS="--flag '-fprofile-arcs -ftest-coverage'"

    - name: Test FPM example build
      run: |
        make test ARGS="--target test_system_fpm_example"

    - name: Test CMake example build
      run: |
        make test ARGS="--target test_system_cmake_example"

    - name: Generate coverage report
      if: always()
      run: |
        gcovr --root . --exclude 'thirdparty/*' --exclude 'build/*' --exclude 'doc/*' --xml -o coverage.xml --print-summary

    - name: Upload coverage to Codecov
      if: always()
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
